### ISSUE TITLE
A question about vqvae.py

### ISSUE THREAD

**Issue by wwma** [junxia97/Mole-BERT#4]
Thanks for your great work!
In vqvae.py Line 248 `e, e_q_loss = vq_layer(node_rep)`
if there miss a variate? I think it should be `e, e_q_loss = vq_layer(node_rep,e)`
But i have no idea about which shoule be "e".

**Comment by ecust-hc** [comment]
I have the same question,do you solve this?

**Comment by ecust-hc** [comment]
Traceback (most recent call last):
  File "vqvae.py", line 390, in <module>
    main()
  File "vqvae.py", line 372, in main
    train_loss = train_vae(args, epoch, model_list, loader, optimizer_list, device)
  File "vqvae.py", line 248, in train_vae
    e, e_q_loss = vq_layer(node_rep)
  File "/home/huchao/anaconda3/envs/my-rdkit-env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'e'
e, e_q_loss = vq_layer(node_rep,?) required positional argument: 'e' , e is what?

**Comment by wwma** [comment]
I tried `e, e_q_loss = vq_layer(batch.x,node_rep)` ,and it works.
