### ISSUE TITLE
AttributeError: 'GNN' object has no attribute 'get_codebook_indices'

### ISSUE THREAD

**Issue by ecust-hc** [junxia97/Mole-BERT#5]
Dear author：
when i run "python pretrain",the class of GNN has no attribute  'get_codebook_indices'. what i should do ? thank you for you help.
Iteration: 0it [00:01, ?it/s]
Traceback (most recent call last):
  File "pretrain.py", line 285, in <module>
    main()
  File "pretrain.py", line 274, in main
    train_loss, train_acc_atom, train_acc_bond = train(args, epoch, model_list, tokenizer, dataset, optimizer_list, device)
  File "pretrain.py", line 147, in train
    atom_ids = tokenizer.get_codebook_indices(batch_origin_x, batch1.edge_index, batch_origin_edge)
  File "/home/huchao/anaconda3/envs/my-rdkit-env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'GNN' object has no attribute 'get_codebook_indices'

**Comment by lggaray** [comment]
Same problem here

**Comment by junxia97** [comment]
Sorry for the error. I updated the wrong code. I will upload the correct version asap.
